"""Parser synthesis: unknown samples -> draft source pack (declarative YAML).

Pipeline: sniff -> choose parse stages (structured extractor, or Drain3
templates -> RE2 named-group regexes for free text) -> extract fields from every
sample -> offline mapper votes (lexical + value-shape) -> optional local LLM
suggestions (validated against OCSF and the observed fields) -> mapping specs ->
self-test -> draft stored for human review. Drafts never route traffic until an
admin approves them, at which point the pack is Ed25519-signed.
"""
from __future__ import annotations

import hashlib
import json
import re
import time
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from typing import Any

import yaml

from ..config import Settings
from ..normalizer import ocsf
from ..packs.engine import compile_pack
from ..sniffer import sniff
from . import mapper
from .miner import cluster_patterns, mine

STRUCTURED = ("json", "xml", "kv", "cef", "leef", "csv")
ACTIVITY = {"network_activity": 6, "detection_finding": 1, "authentication": 1, "dns_activity": 1,
            "http_activity": 0, "base_event": 0}
SYSLOG_SEV = {"0": 6, "1": 5, "2": 5, "3": 4, "4": 3, "5": 2, "6": 1, "7": 1}
_WORD_OK = re.compile(r"[A-Za-z]{3}")
_MONTHS = {m.lower() for m in "Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec".split()}


def _slug(s: str) -> str:
    return re.sub(r"[^a-z0-9_\-]+", "_", s.lower()).strip("_") or "unknown"


@dataclass
class Draft:
    doc: dict
    report: dict = field(default_factory=dict)

    @property
    def id(self) -> str:
        return self.doc["id"]

    def yaml(self) -> str:
        head = ("# Draft generated by ULPF aigen. NOT ACTIVE until approved by an admin.\n"
                "# Review parse patterns and mappings; approval signs the pack (Ed25519).\n")
        return head + yaml.safe_dump(self.doc, sort_keys=False, allow_unicode=True, width=200)


def _parse_stages(samples: list[str]) -> tuple[list[dict], str, str, list[str], list[str], list[str]]:
    from ..extractors import get

    sns = [sniff(s) for s in samples]
    fmt = Counter(s.format for s in sns).most_common(1)[0][0]
    env = "syslog" if Counter(s.envelope for s in sns).most_common(1)[0][0] == "syslog" or fmt == "syslog" else ""
    tags = sorted(set.intersection(*(s.tags for s in sns)))
    stages: list[dict] = []
    src = None
    bodies = list(samples)
    if env:
        stages.append({"type": "syslog"})
        src = "message"
        bodies = []
        for s in samples:
            try:
                bodies.append(get("syslog")(s, {}).get("message", s))
            except Exception:
                bodies.append(s)
    notes: list[str] = []
    if fmt in STRUCTURED:
        st: dict[str, Any] = {"type": fmt}
        if src:
            st["source"] = src
        stages.append(st)
    else:
        pats = cluster_patterns(mine(bodies))
        notes.append(f"drain3: {len(pats)} template(s) from {len(bodies)} message(s)")
        st = {"type": "regex", "patterns": [p for p, _, _ in pats[:12]], "required": False}
        if src:
            st["source"] = src
        stages.append(st)
    return stages, fmt, env, notes, tags, bodies


def _common_tokens(samples: list[str], fmt: str) -> list[str]:
    if fmt == "kv":
        keysets = [set(re.findall(r"(?:^|\s)([A-Za-z_][\w.\-]*=)", s)) for s in samples]
        common = set.intersection(*keysets) if keysets else set()
        return sorted(common, key=len, reverse=True)[:2]
    if fmt == "cef":
        heads = {"|".join(s[s.find("CEF:"):].split("|")[:3]) for s in samples if "CEF:" in s}
        return [heads.pop()] if len(heads) == 1 else []
    if fmt == "leef":
        heads = {"|".join(s[s.find("LEEF:"):].split("|")[:3]) for s in samples if "LEEF:" in s}
        return [heads.pop()] if len(heads) == 1 else []
    if fmt == "json":
        keysets = [set(re.findall(r'"([A-Za-z_][\w.\-]*)"\s*:', s)) for s in samples]
        common = set.intersection(*keysets) if keysets else set()
        return [f'"{k}"' for k in sorted(common, key=len, reverse=True)[:2]]
    toksets = [set(s.split()) for s in samples]
    common = set.intersection(*toksets) if toksets else set()
    good = [t for t in common if _WORD_OK.search(t) and t.lower().rstrip(":,") not in _MONTHS
            and not re.fullmatch(r"<\d+>.*", t) and not re.search(r"\d{2}:\d{2}", t)]
    return sorted(good, key=len, reverse=True)[:2]


def _field_values(pack_doc: dict, samples: list[str]) -> tuple[dict[str, list[str]], list[dict], int]:
    cp = compile_pack(pack_doc)
    values: dict[str, list[str]] = defaultdict(list)
    per_sample: list[dict] = []
    failures = 0
    for s in samples:
        try:
            f = cp.extract(s)
            f.pop("__consumed_sources__", None)
        except Exception:
            failures += 1
            continue
        per_sample.append(f)
        for k, v in f.items():
            if isinstance(v, (dict, list)) or v in (None, ""):
                continue
            if len(values[k]) < 8 and str(v) not in values[k]:
                values[k].append(str(v)[:200])
    return dict(values), per_sample, failures


def _vote(per_sample: list[dict]) -> tuple[str, dict[str, mapper.FieldMatch]]:
    classes: Counter = Counter()
    votes: dict[str, Counter] = defaultdict(Counter)
    best: dict[tuple[str, str], mapper.FieldMatch] = {}
    for f in per_sample:
        g = mapper.infer(f)
        classes[g.class_name] += 1
        for path, m in g.matches.items():
            votes[path][m.raw] += 1
            k = (path, m.raw)
            if k not in best or m.score > best[k].score:
                best[k] = m
    cls = classes.most_common(1)[0][0] if classes else "base_event"
    n = max(1, len(per_sample))
    chosen: dict[str, mapper.FieldMatch] = {}
    used: set[str] = set()
    for path, c in sorted(votes.items(), key=lambda kv: -kv[1].most_common(1)[0][1]):
        raw, cnt = c.most_common(1)[0]
        if cnt / n >= 0.5 and raw not in used:
            chosen[path] = best[(path, raw)]
            used.add(raw)
    return cls, chosen


def synthesize(samples: list[str], settings: Settings, vendor: str | None = None, product: str | None = None,
               use_llm: str = "auto", registry=None) -> Draft:
    samples = [s.rstrip("\r\n") for s in samples if s.strip()][:500]
    if len(samples) < 3:
        raise ValueError("need at least 3 sample lines to synthesize a parser")
    t0 = time.time()
    stages, fmt, env, notes, tags, bodies = _parse_stages(samples)
    probe = {"id": "draft.probe", "version": "0", "vendor": "x", "product": "x", "match": {},
             "parse": stages, "classes": [{"class": "base_event"}]}
    values, per_sample, extract_failures = _field_values(probe, samples)
    cls, matches = _vote(per_sample)

    llm_info: dict[str, Any] = {"used": False}
    if use_llm != "off":
        try:
            from .llm import LLMUnavailable, OllamaClient, suggest

            client = OllamaClient(settings)
            if client.available():
                cands = list(dict.fromkeys([cls, "network_activity", "detection_finding", "authentication",
                                            "http_activity", "dns_activity"]))
                sug = suggest(client, values, cands, samples[:3])
                llm_info = {"used": True, "model": client.model, "rejected": sug["rejected"][:20],
                            "class": sug["class"]}
                if sug["class"]:
                    cls = sug["class"]
                used = {m.raw for m in matches.values()}
                for path, raw in sug["mapping"].items():
                    if path not in matches and raw not in used:
                        matches[path] = mapper.FieldMatch(raw, path, 0.55, "llm")
                        used.add(raw)
                vendor = vendor or sug["vendor"] or None
                product = product or sug["product"] or None
            else:
                llm_info["reason"] = f"model {client.model} not reachable at {client.url}"
        except Exception as exc:  # LLMUnavailable, host not allowed, parse errors -> offline mapper only
            llm_info["reason"] = str(exc)[:200]
            if use_llm == "on":
                raise

    if cls != "base_event":
        matches = {p: m for p, m in matches.items()
                   if p in ("severity_id", "disposition") or ocsf.known_path(cls, p)}
    if fmt in STRUCTURED:  # the stage input is the whole body; mapping it would just duplicate raw_data
        matches = {p: m for p, m in matches.items() if m.raw != stages[-1].get("source")}
    if "time" not in matches and "date" in values and "time" in values:
        matches.pop("time", None)
        date_time = True
    else:
        date_time = False
    mapping: dict[str, Any] = {}
    confidence: dict[str, Any] = {}
    for path, m in sorted(matches.items()):
        conf = {"raw": m.raw, "score": m.score, "method": m.method}
        if path == "time":
            mapping["time"] = {"field": m.raw, "cast": "timestamp"}
        elif path == "severity_id":
            continue
        elif path == "disposition":
            vals = values.get(m.raw, [])
            mapping["disposition_id"] = {"field": m.raw, "map": {v.lower(): mapper.disposition_id(v) for v in vals},
                                         "default": 0}
            if ocsf.known_path(cls, "disposition"):
                mapping["disposition"] = m.raw
            confidence["disposition_id"] = conf
            continue
        else:
            mapping[path] = m.raw
        confidence[path] = conf
    if date_time and ocsf.known_path(cls, "time"):
        mapping["time"] = {"template": "{date} {time}", "cast": "timestamp"}
        confidence["time"] = {"raw": ["date", "time"], "score": 0.9, "method": "date+time"}
    if "time" not in mapping and env == "syslog":
        mapping["time"] = {"field": "syslog_timestamp", "cast": "timestamp"}
        confidence["time"] = {"raw": "syslog_timestamp", "score": 1.0, "method": "envelope"}
    if "device.hostname" not in mapping and env == "syslog" and ocsf.known_path(cls, "device.hostname"):
        mapping["device.hostname"] = "syslog_host"
        confidence["device.hostname"] = {"raw": "syslog_host", "score": 1.0, "method": "envelope"}
    if stages[-1]["type"] == "regex" and ocsf.known_path(cls, "message") and "message" not in mapping:
        mapping["message"] = "message"  # keep the full free-text body (lossless)
    sev_m = matches.get("severity_id")
    if sev_m:
        severity: Any = {"field": sev_m.raw, "map": {v.lower(): mapper.severity_id(v) or 1
                                                   for v in values.get(sev_m.raw, [])}, "default": 1}
    elif env == "syslog":
        severity = {"field": "syslog_severity", "map": SYSLOG_SEV, "default": 1}
    else:
        severity = {"const": 1}

    fp = hashlib.sha256("\n".join(sorted(values)).encode()).hexdigest()[:8]
    pid = f"{_slug(vendor)}.{_slug(product)}" if vendor and product else f"draft.src_{fp}"
    match: dict[str, Any] = {"formats": tags or [fmt]}
    toks = _common_tokens(bodies, fmt)
    if toks:
        match["contains"] = toks
    doc = {
        "id": pid, "version": "0.1", "vendor": vendor or "Unknown vendor", "product": product or f"Source {fp}",
        "category": "auto-generated",
        "description": f"Auto-generated from {len(samples)} samples ({fmt}{'/syslog' if env == 'syslog' else ''}).",
        "priority": 30,
        "provenance": {
            "author": "ulpf-aigen", "generated_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
            "samples": len(samples), "sample_sha256": [hashlib.sha256(s.encode()).hexdigest()[:16] for s in samples[:5]],
            "llm": llm_info, "notes": notes, "field_confidence": confidence, "approved_by": None,
        },
        "match": match,
        "parse": stages,
        "severity_id": severity,
        "classes": [{"name": "default", "class": cls, "activity_id": {"const": ACTIVITY.get(cls, 0)},
                     "mapping": mapping}],
        "tests": [{"input": s, "expect_class": cls} for s in samples[:3]],
    }
    draft = Draft(doc)
    from .selftest import selftest

    draft.report = selftest(doc, samples, settings, registry)
    draft.report["extract_failures"] = extract_failures
    draft.report["synth_seconds"] = round(time.time() - t0, 3)
    return draft


def fields_preview(draft: Draft, samples: list[str]) -> list[dict]:
    """Per-sample (raw -> extracted fields) preview for the onboarding UI."""
    cp = compile_pack(draft.doc)
    out = []
    for s in samples[:5]:
        try:
            f = cp.extract(s)
            f.pop("__consumed_sources__", None)
        except Exception as exc:
            f = {"_error": str(exc)}
        out.append({"raw": s, "fields": json.loads(json.dumps(f, default=str))})
    return out
